import React, { useState } from 'react';

interface Props {
  transcript: string;
  fileName:   string;
  onReset:    () => void;
}

export function TranscriptView({ transcript, fileName, onReset }: Props) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(transcript);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback for older browsers
      const ta = document.createElement('textarea');
      ta.value = transcript;
      ta.style.position = 'fixed';
      ta.style.opacity  = '0';
      document.body.appendChild(ta);
      ta.select();
      document.execCommand('copy');
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleDownloadTxt = () => {
    const base = fileName.replace(/\.[^/.]+$/, '') || 'transcript';
    const blob = new Blob([transcript], { type: 'text/plain;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${base}-transcript.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadMd = () => {
    const base     = fileName.replace(/\.[^/.]+$/, '') || 'transcript';
    const mdContent = `# Transcript: ${base}\n\n_Generated by Voice Transcriber on ${new Date().toLocaleDateString()}_\n\n---\n\n${transcript}`;
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `${base}-transcript.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  // Line count and word count for the stats bar
  const lines = transcript.split('\n').filter(l => l.trim()).length;
  const words = transcript.split(/\s+/).filter(Boolean).length;

  return (
    <div className="w-full max-w-3xl mx-auto animate-slide-up">

      {/* Header card */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm mb-4 p-5">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="min-w-0">
            <div className="flex items-center gap-2 mb-1">
              <div className="w-6 h-6 bg-green-100 rounded-full flex items-center justify-center flex-shrink-0">
                <svg className="w-3.5 h-3.5 text-green-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>
              </div>
              <span className="text-xs font-semibold text-green-700 uppercase tracking-wide">Transcript Ready</span>
            </div>
            <h2 className="font-bold text-slate-900 truncate">{fileName}</h2>
            <div className="flex items-center gap-3 mt-1 text-xs text-slate-400">
              <span>{lines} speaker turns</span>
              <span>·</span>
              <span>{words.toLocaleString()} words</span>
              <span>·</span>
              <span>{(transcript.length / 1024).toFixed(1)} KB</span>
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={handleCopy}
              className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-sm font-medium transition-colors ${
                copied
                  ? 'bg-green-100 text-green-700'
                  : 'bg-surface-100 hover:bg-surface-200 text-slate-700'
              }`}
            >
              {copied ? (
                <><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                </svg>Copied!</>
              ) : (
                <><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                    d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                </svg>Copy</>
              )}
            </button>

            <button
              onClick={handleDownloadTxt}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-sm font-medium bg-surface-100 hover:bg-surface-200 text-slate-700 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              .txt
            </button>

            <button
              onClick={handleDownloadMd}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-sm font-medium bg-surface-100 hover:bg-surface-200 text-slate-700 transition-colors"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
              </svg>
              .md
            </button>

            <button
              onClick={onReset}
              className="flex items-center gap-1.5 px-3 py-2 rounded-xl text-sm font-medium bg-brand-600 hover:bg-brand-700 text-white transition-colors"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2}
                  d="M12 4v1m6 11h2m-6 0h-2v4m0-11v3m0 0h.01M12 12h4.243m-4.243 0L9 15m3-3l-3-3" />
              </svg>
              New
            </button>
          </div>
        </div>
      </div>

      {/* Transcript body */}
      <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
        <div className="px-4 py-3 bg-surface-50 border-b border-slate-100 flex items-center justify-between">
          <span className="text-xs font-semibold text-slate-500 uppercase tracking-wide">Transcript</span>
          <span className="text-xs text-slate-400">Scroll to read · Use Copy or Download buttons above to export</span>
        </div>
        <div className="p-6 max-h-[60vh] overflow-y-auto">
          <pre className="whitespace-pre-wrap break-words font-mono text-sm leading-7 text-slate-700">
            {transcript}
          </pre>
        </div>
      </div>

      {/* Tip: use with meeting-notes */}
      <div className="mt-4 p-4 bg-brand-50 rounded-2xl border border-brand-100">
        <p className="text-sm text-brand-800">
          <span className="font-semibold">Next step:</span> Copy this transcript and paste it into{' '}
          <strong>Meeting Notes Generator</strong> (coming soon) to get structured summaries, action items, and decisions.
        </p>
      </div>
    </div>
  );
}
